import { useState } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { View, Text, ScrollView, Pressable, TextInput, StyleSheet } from 'react-native';

const blue='#0b6f8a'; const dark='#075c73';
const services=[
 ['💻','Manutenção de Computadores','Diagnóstico, reparação, upgrades e otimização.'],
 ['🌐','Redes Corporativas','Instalação e configuração de redes cabeadas e Wi‑Fi.'],
 ['🖥️','Infraestrutura e Servidores','Windows Server, Linux, virtualização e backup.'],
 ['📱','Assistência para Celulares','Configuração, atualização, backup e suporte.'],
 ['📹','Câmeras de Segurança','Instalação e configuração de CFTV, DVR e NVR.'],
 ['🛠️','Suporte Remoto','Atendimento rápido para empresas e residências.']
];
export default function Home(){const [q,setQ]=useState(''); return <SafeAreaView style={s.safe}><ScrollView style={s.screen} contentContainerStyle={s.content}>
 <View style={s.header}><View style={s.logo}><Text style={s.logoText}>B</Text></View><View style={{flex:1}}><Text style={s.brand}>BiteFixes</Text><Text style={s.tag}>Reparos inteligentes para sua tecnologia.</Text></View><Pressable style={s.bitey}><Text style={s.biteyText}>🤖 Bitey</Text></Pressable></View>
 <View style={s.hero}><Text style={s.kicker}>SOLUÇÕES INTELIGENTES EM TI</Text><Text style={s.h1}>Tecnologia que funciona para você.</Text><Text style={s.heroText}>Computadores, notebooks, celulares, redes, servidores e sistemas de monitoramento.</Text><View style={s.actions}><Pressable style={s.primary}><Text style={s.primaryText}>Solicitar orçamento</Text></Pressable><Pressable style={s.secondary}><Text style={s.secondaryText}>Falar com Bitey</Text></Pressable></View></View>
 <Text style={s.section}>Serviços</Text><Text style={s.sectionSub}>Suporte para empresas e residências, presencial e remoto.</Text>
 <View style={s.grid}>{services.map(([icon,title,desc])=><Pressable key={title} style={s.card}><Text style={s.icon}>{icon}</Text><Text style={s.cardTitle}>{title}</Text><Text style={s.cardText}>{desc}</Text><Text style={s.more}>Ver serviço ›</Text></Pressable>)}</View>
 <View style={s.contact}><Text style={s.contactTitle}>Precisa de ajuda?</Text><Text style={s.contactText}>Conte o que você precisa e a BiteFixes orienta o próximo passo.</Text><TextInput value={q} onChangeText={setQ} placeholder="Descreva seu problema..." placeholderTextColor="#80919a" multiline style={s.input}/><Pressable style={s.primary}><Text style={s.primaryText}>Enviar solicitação</Text></Pressable><Text style={s.address}>Rua Garibaldi 194 · Esteio – RS · Brasil</Text></View>
 <Text style={s.footer}>20+ anos de experiência · Atendimento presencial e remoto</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5fafb'},screen:{flex:1,backgroundColor:'#fff'},content:{paddingBottom:32},header:{minHeight:72,paddingHorizontal:18,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:'#e3edf0'},logo:{width:42,height:42,borderRadius:12,backgroundColor:blue,alignItems:'center',justifyContent:'center'},logoText:{color:'#fff',fontSize:20,fontWeight:'900'},brand:{fontSize:17,fontWeight:'900',color:'#17384f'},tag:{fontSize:9,color:'#73858f',marginTop:1},bitey:{paddingHorizontal:11,paddingVertical:8,borderRadius:10,backgroundColor:'#eaf6f8'},biteyText:{color:dark,fontSize:12,fontWeight:'800'},hero:{margin:16,padding:22,borderRadius:20,backgroundColor:'#edf8fa',borderWidth:1,borderColor:'#cce6ec'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:blue},h1:{fontSize:30,lineHeight:35,fontWeight:'900',color:'#17384f',marginTop:8},heroText:{fontSize:14,lineHeight:21,color:'#536b77',marginTop:9},actions:{flexDirection:'row',gap:9,marginTop:17},primary:{backgroundColor:blue,borderRadius:10,paddingHorizontal:15,paddingVertical:11,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800',fontSize:12},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:'#9bc7d2',borderRadius:10,paddingHorizontal:15,paddingVertical:11,alignItems:'center'},secondaryText:{color:dark,fontWeight:'800',fontSize:12},section:{fontSize:22,fontWeight:'900',color:'#17384f',paddingHorizontal:18,marginTop:6},sectionSub:{fontSize:12,color:'#788b95',paddingHorizontal:18,marginTop:4,marginBottom:11},grid:{paddingHorizontal:14,gap:9},card:{padding:15,borderRadius:14,borderWidth:1,borderColor:'#dce9ed',backgroundColor:'#fff',shadowColor:'#18344d',shadowOpacity:.05,shadowRadius:8,elevation:1},icon:{fontSize:24},cardTitle:{fontSize:14,fontWeight:'850',color:'#183b51',marginTop:8},cardText:{fontSize:11.5,lineHeight:17,color:'#667b86',marginTop:4},more:{fontSize:11,fontWeight:'800',color:blue,marginTop:9},contact:{margin:16,marginTop:24,padding:18,borderRadius:17,backgroundColor:'#f5fafb',borderWidth:1,borderColor:'#d6e8ed'},contactTitle:{fontSize:20,fontWeight:'900',color:'#17384f'},contactText:{fontSize:12,color:'#657a85',marginTop:4,marginBottom:12},input:{minHeight:85,maxHeight:150,borderWidth:1,borderColor:'#bdd6de',backgroundColor:'#fff',borderRadius:11,padding:11,color:'#18344d',fontSize:13,textAlignVertical:'top',marginBottom:9},address:{fontSize:10,color:'#7d919b',marginTop:12,textAlign:'center'},footer:{fontSize:10,color:'#91a0a7',textAlign:'center',paddingHorizontal:18,marginTop:4}});